VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "I_CopyFetchFormView"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("TableManager.Forms")

'Option Explicit
'
'Public Function ShowDialog(ByVal viewModel As Object) As Boolean
'End Function
'
'Public Property Get Model() As CopyFetchClass
'End Property
'
'Public Property Set Model(ByVal value As CopyFetchClass)
'End Property
'
'Public Property Let Source(ByVal Src As String)
'End Property
'
'Public Property Let Destination(ByVal Dst As String)
'End Property
'
'Public Property Get Form() As UserForm
'End Property
'
'
'
