VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "I_DataBase"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function ArrayFromDataBase(ByVal Parameters As String) As Variant
End Function

Public Sub ArrayToDataBase(ByRef MyArray() As Variant, ByVal Parameters As String)
End Sub

Public Sub OpenDataBase()
End Sub

Public Sub CloseDataBase()
End Sub

